from docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4

RUN mkdir -p /data/elasticsearch
RUN chown -R elasticsearch:elasticsearch /data/elasticsearch

#USER root
#RUN sysctl -w vm.max_map_count=262144
