pipeline {
    agent {
    	docker {
    		image 'maven:latest'
				args '-v /root/.m2:/root/.m2'
    	}
    }

    stages {
        stage('Build') {
					steps {
						sh 'mvn -B -DskipTests -f uniknowledge-rest-api/pom.xml clean package'
        	}

        }
        stage('Test') {
            steps {
							sh 'mvn -f uniknowledge-rest-api/pom.xml -e test'
            }
        }
        stage('Deploy') {
            steps {
							sh 'mvn -f uniknowledge-rest-api/pom.xml clean install'
            }
        }
    }
}
